// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package escape

import (
	"fmt"

	"cmd/compile/internal/base"
	"cmd/compile/internal/ir"
	"cmd/compile/internal/types"
)

// DetectForwarders walks fn's body looking for the trivial-
// forwarder shapes that Phase F4 can synthesise compute fns for.
// When the body matches, it sets fn.GdForwarder so the synthesis
// pass downstream can emit a parallel `func(carrier, heapMask,
// depth) uint64` that reads the delegate's mask at runtime.
//
// The detector is conservative on purpose:
//
//   - **Body shape**: exactly one statement that is either
//     `return inner.M(args...)` (single-result func) or
//     `inner.M(args...)` (void). Multi-statement bodies, branches,
//     and any pre/post-call work disqualify the function — F4 has
//     no way to express "delegate's mask plus extra escape edges".
//
//   - **Args**: exact pass-through of the wrapper's parameters in
//     declaration order, no slicing, no munging, no extras. If
//     the wrapper repackages args, the delegate's mask doesn't
//     describe the wrapper's escape facts.
//
//   - **Inner callable**: must be a stable pointer-bearing field
//     of the receiver (`w.field.M(...)`) for the iface case, or
//     a captured variable for the closure case (deferred — F3
//     starts with the receiver-field shape only).
//
// Run time: must be after escape analysis populates leaks
// (otherwise the detector can't sanity-check that the wrapper's
// own static mask is consistent with "delegate-derived"). We hook
// it in escape.Batch.finish.
//
// Output: ir.Func.GdForwarder = &GdForwarderInfo{...}. F4
// consumes; if F4 is not yet active, the field is inert (the
// wrapper continues to use its conservative static mask).
//
// See doc/gd/escape-bits.md §F3.
func DetectForwarders(gd *base.Invocation, fn *ir.Func) {
	if fn == nil || fn.GdForwarder != nil {
		return
	}
	if fn.Type() != nil && fn.Type().HasShape() {
		return
	}
	// Skip compiler-autogenerated wrappers (embedded-iface
	// promotion stubs etc.). Their bodies look like trivial
	// forwarders to the matcher but synthesizing + installing
	// for them confuses the linker's content-addressable itab
	// dedup, leading to duplicate type descriptors in cross-
	// package iface dispatches. F4's value is in real user-
	// written wrappers; skip the autogen pool.
	if !fn.Pos().IsKnown() {
		return
	}
	info, reason := matchForwarderBody(fn)
	if info == nil {
		if gd.Debug.GdForwarder >= 2 {
			gd.WarnfAt(fn.Pos(), "gd:forwarder reject %v: %s", fn.Sym(), reason)
		}
		return
	}
	fn.GdForwarder = info
	if gd.Debug.GdForwarder != 0 {
		gd.WarnfAt(fn.Pos(), "gd:forwarder detected %v: shape=%d innerCall=%v", fn.Sym(), info.Shape, info.InnerCall)
	}
}

// matchForwarderBody returns a populated GdForwarderInfo when fn's
// body fits the trivial-forwarder template, plus an empty reason.
// On rejection it returns (nil, reasonString) so the optional
// debug log can explain why a candidate was filtered out.
//
// Accepted body shapes (by the time escape sees fn.Body):
//
//  1. Single-stmt:
//     return inner.M(args)             // single result
//     inner.M(args)                    // void
//
//  2. Two-stmt (multi-result, after typecheck hoists the call into
//     autotmps so the ReturnStmt only carries plain Names):
//     autotmp1, ... autotmpN = inner.M(args)
//     return autotmp1, ... autotmpN
func matchForwarderBody(fn *ir.Func) (*ir.GdForwarderInfo, string) {
	body := fn.Body
	if len(body) == 0 || len(body) > 2 {
		return nil, fmt.Sprintf("body has %d stmts, want 1 or 2", len(body))
	}
	call := callFromForwarderBody(body)
	if call == nil {
		// One-shot diagnostic for the common rejection.
		if len(body) == 1 {
			if r, ok := body[0].(*ir.ReturnStmt); ok {
				return nil, fmt.Sprintf("ReturnStmt with %d results, init=%d: results=%v init=%v", len(r.Results), len(r.Init()), r.Results, r.Init())
			}
			return nil, fmt.Sprintf("body[0] is %T, not return/call", body[0])
		}
		return nil, fmt.Sprintf("two-stmt body did not match `tmp... = call; return tmp...`: body[0]=%T body[1]=%T", body[0], body[1])
	}
	if !argsMatchParams(call, fn) {
		return nil, "args don't pass through 1:1"
	}
	sel, ok := call.Fun.(*ir.SelectorExpr)
	if !ok {
		return nil, fmt.Sprintf("call.Fun is %T, not SelectorExpr", call.Fun)
	}
	if call.Op() != ir.OCALLINTER {
		return nil, fmt.Sprintf("call.Op=%v, not OCALLINTER", call.Op())
	}
	innerSel, ok := sel.X.(*ir.SelectorExpr)
	if !ok || !innerIsRecvFieldIface(sel.X, fn) || innerSel.Selection == nil {
		return nil, "inner is not receiver-field iface"
	}
	methodIdx := int(sel.Offset() / int64(types.PtrSize))
	return &ir.GdForwarderInfo{
		Shape:       ir.GdForwarderRecvField,
		InnerCall:   call,
		MethodIdx:   methodIdx,
		FieldOffset: innerSel.Selection.Offset,
	}, ""
}

// callFromForwarderBody walks fn.Body to find the single inner
// CallExpr the wrapper delegates to, across the body shapes
// matchForwarderBody accepts. Returns nil when the body doesn't
// match.
//
// Two physical shapes get the same logical match:
//
//  1. **Single-stmt return-of-call** (single-result fn):
//     body[0] = ReturnStmt{Results: [CallExpr]}
//
//  2. **Multi-result return** (typechecker decomposes the call
//     into autotmps via ir.InitExpr; the AssignListStmt lives in
//     Results[0]'s Init list):
//     body[0] = ReturnStmt{Results: [InitExpr(autotmp1), autotmp2, ...]}
//     Results[0].Init = [AssignListStmt(autotmp1..N = CallExpr)]
//     The CallExpr is the inner call we want.
//
//  3. **Void call**: body[0] is the CallExpr itself.
func callFromForwarderBody(body []ir.Node) *ir.CallExpr {
	if len(body) == 1 {
		switch s := body[0].(type) {
		case *ir.ReturnStmt:
			if call := callFromReturn(s); call != nil {
				return call
			}
		case *ir.CallExpr:
			return s
		}
		return nil
	}
	// len == 2: pre-multiExpr-style decomposition (also used for
	// some manually-spelt forwarders and for compiler-generated
	// pointer-receiver wrappers around value-receiver methods).
	return matchTwoStmtForwarder(body[0], body[1])
}

// matchTwoStmtForwarder accepts the two-stmt shape:
//
//	tmp1, tmpN = inner(args)            // *ir.AssignListStmt
//	return tmp1, tmpN                    // *ir.ReturnStmt
//
// Compiler-generated pointer-receiver wrappers spread the receiver
// load before the call, e.g.
//
//	r := *recv                            // optional
//	tmp1, tmpN = r.inner.M(args)
//	return tmp1, tmpN
//
// That third statement bumps body length to 3+ and the matcher
// rejects (matchForwarderBody gates len <= 2). Real method-on-
// concrete-type wrappers are always direct (ODOTMETH /
// OCALLMETH), which the OCALLINTER gate also rejects later.
func matchTwoStmtForwarder(s0, s1 ir.Node) *ir.CallExpr {
	asgn, ok := s0.(*ir.AssignListStmt)
	if !ok {
		return nil
	}
	if len(asgn.Rhs) != 1 {
		return nil
	}
	call, ok := asgn.Rhs[0].(*ir.CallExpr)
	if !ok {
		return nil
	}
	ret, ok := s1.(*ir.ReturnStmt)
	if !ok {
		return nil
	}
	if len(ret.Results) != len(asgn.Lhs) {
		return nil
	}
	for i, r := range ret.Results {
		if asLeafName(r) != asLeafName(asgn.Lhs[i]) {
			return nil
		}
	}
	return call
}

// callFromReturn extracts the inner CallExpr from a ReturnStmt
// that either:
//   - returns a single CallExpr (single-result wrapper), or
//   - returns autotmps fed by an InitExpr-wrapped AssignListStmt
//     (multi-result wrapper after typecheck's multiExpr split).
func callFromReturn(s *ir.ReturnStmt) *ir.CallExpr {
	if len(s.Results) == 0 {
		return nil
	}
	// Single-result: Results[0] is the call directly.
	if len(s.Results) == 1 {
		if call, ok := s.Results[0].(*ir.CallExpr); ok {
			return call
		}
	}
	// Multi-result: Results[0] is an InitExpr-wrapped autotmp;
	// the AssignListStmt sits in Results[0].Init().
	first := s.Results[0]
	leafs := make([]*ir.Name, 0, len(s.Results))
	for _, r := range s.Results {
		n := asLeafName(r)
		if n == nil {
			return nil
		}
		leafs = append(leafs, n)
	}
	for _, in := range first.Init() {
		asgn, ok := in.(*ir.AssignListStmt)
		if !ok || len(asgn.Rhs) != 1 {
			continue
		}
		call, ok := asgn.Rhs[0].(*ir.CallExpr)
		if !ok {
			continue
		}
		if len(asgn.Lhs) != len(leafs) {
			continue
		}
		match := true
		for i, lhs := range asgn.Lhs {
			if asLeafName(lhs) != leafs[i] {
				match = false
				break
			}
		}
		if match {
			return call
		}
	}
	return nil
}

// asLeafName strips off OCONV/OCONVNOP wrappers and returns the
// underlying *ir.Name, or nil if the expression isn't ultimately
// a Name.
func asLeafName(n ir.Node) *ir.Name {
	for {
		switch x := n.(type) {
		case *ir.Name:
			return x
		case *ir.ConvExpr:
			n = x.X
		default:
			return nil
		}
	}
}

// argsMatchParams reports whether call's args are exactly fn's
// declared parameters (excluding the receiver) in source order,
// passed unmodified. Variadic spreads (`f(args...)`) are accepted
// only when call's declared signature also takes a variadic
// matching the wrapper's last param.
func argsMatchParams(call *ir.CallExpr, fn *ir.Func) bool {
	params := fn.Type().Params()
	if len(call.Args) != len(params) {
		return false
	}
	// fn.Dcl lists the receiver (if any) first, then params, then
	// return slots, then locals — all PPARAM/PPARAMOUT/PAUTO. We
	// want PPARAMs only, AFTER skipping the receiver.
	hasRecv := fn.Type().Recv() != nil
	var paramNames []*ir.Name
	skipped := false
	for _, n := range fn.Dcl {
		if n.Class != ir.PPARAM {
			continue
		}
		if hasRecv && !skipped {
			skipped = true
			continue
		}
		paramNames = append(paramNames, n)
		if len(paramNames) == len(params) {
			break
		}
	}
	if len(paramNames) != len(params) {
		return false
	}
	for i, arg := range call.Args {
		name := asLeafName(arg)
		if name == nil || name != paramNames[i] {
			return false
		}
	}
	return true
}

// innerIsRecvFieldIface reports whether expr is `recv.field`
// where recv is fn's receiver and field's type is an interface
// (with at least one method). This is the inner iface that the
// wrapper delegates to in the recv-field forwarder shape.
func innerIsRecvFieldIface(expr ir.Node, fn *ir.Func) bool {
	sel, ok := expr.(*ir.SelectorExpr)
	if !ok {
		return false
	}
	recv := receiverName(fn)
	if recv == nil {
		return false
	}
	xName, ok := sel.X.(*ir.Name)
	if !ok || xName != recv {
		return false
	}
	if sel.Selection == nil || sel.Selection.Type == nil {
		return false
	}
	t := sel.Selection.Type
	if !t.IsInterface() {
		return false
	}
	if len(t.AllMethods()) == 0 {
		return false // empty iface — no method to delegate to.
	}
	return true
}

// receiverName returns fn's receiver *ir.Name, or nil for non-method
// functions.
func receiverName(fn *ir.Func) *ir.Name {
	if fn == nil || fn.Type() == nil || fn.Type().Recv() == nil {
		return nil
	}
	for _, n := range fn.Dcl {
		if n.Class == ir.PPARAM && n.Name() == n && n.Sym() != nil && n.Sym().Name == ".this" {
			return n
		}
	}
	// Receiver is the first PPARAM in source order (Go's
	// frontend names it via the source ident; check by Type
	// matching the receiver's type in the signature).
	recvType := fn.Type().Recv().Type
	for _, n := range fn.Dcl {
		if n.Class != ir.PPARAM {
			continue
		}
		if types.Identical(n.Type(), recvType) {
			return n
		}
	}
	return nil
}
