// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package escape

import (
	"cmd/compile/internal/base"
	"cmd/compile/internal/ir"
	"cmd/compile/internal/typecheck"
	"cmd/compile/internal/types"
	"cmd/internal/src"
)

// synthRegistered tracks the synthesised compute-fn names that
// have already been appended to typecheck.Target.Funcs. The
// detector + wrapper-deduplication can both produce duplicate
// requests (same wrapper Func walked twice, or two ABI-wrapper
// pairs sharing a base wrapper); without a registry guard we'd
// enqueue the same cfn twice and gc.prepareFunc → ir.InitLSym
// fires its "already initialised" assertion.
var synthRegistered = map[string]*ir.Func{}

// SynthesizeForwarderComputeFns walks the package's functions
// and, for each one tagged by DetectForwarders with
// fn.GdForwarder, builds a tiny synthetic compute fn that
// tail-calls runtime.resolveForwardedRecvFieldMask with the
// detected (fieldOffset, methodIdx) constants baked in.
//
// The synthetic fn is added to typecheck.Target.Funcs so walk
// compiles it. Its symbol is recorded back on
// fn.GdForwarder.SyntheticComputeFn so reflectdata's
// FinalizeItabMasks and staticdata's WriteFuncSyms can install
// it (with bit 0 set) into the wrapper's mask carrier.
//
// Runs after escape.Funcs (DetectForwarders has populated the
// GdForwarder fields) and before reflectdata.FinalizeItabMasks
// (which consumes the install symbol).
//
// See doc/gd/escape-bits.md §F4.
func SynthesizeForwarderComputeFns(funcs []*ir.Func) {
	// Snapshot the input; we'll append synthesised fns to
	// typecheck.Target.Funcs which is the same backing slice.
	for _, fn := range funcs {
		if fn.GdForwarder == nil {
			continue
		}
		if fn.GdForwarder.SyntheticComputeFn != nil {
			continue
		}
		if fn.GdForwarder.Shape != ir.GdForwarderRecvField {
			continue // F4 only handles the recv-field shape so far.
		}
		linkName := fn.Linksym().Name
		synthName := ".gdfwd." + linkName
		if existing, ok := synthRegistered[synthName]; ok {
			// Re-derive: a different wrapper *Func with the
			// same linksym name (e.g. ABI wrapper pairs) hit
			// the same synth — share it. The constants must
			// match because they're derived from the same
			// receiver type + method.
			fn.GdForwarder.SyntheticComputeFn = existing
			continue
		}
		cfn := buildForwarderComputeFn(fn, synthName)
		if cfn == nil {
			continue
		}
		fn.GdForwarder.SyntheticComputeFn = cfn
		synthRegistered[synthName] = cfn
		// Note: typecheck.DeclFunc (called by buildForwarder
		// ComputeFn) already appends cfn to Target.Funcs.
		// Appending again here would enqueue the same fn twice
		// and trigger ir.InitLSym's "called twice" assertion.
		if base.Debug.GdForwarder != 0 {
			base.WarnfAt(fn.Pos(), "gd:forwarder synthesised compute fn %v for %v (fieldOffset=%d methodIdx=%d)", cfn.Sym(), fn.Sym(), fn.GdForwarder.FieldOffset, fn.GdForwarder.MethodIdx)
		}
	}
}

// buildForwarderComputeFn synthesises an ir.Func equivalent to:
//
//	func .gdfwd.<wrapperLinkName>(carrier unsafe.Pointer, heapMask uint64, depth int) uint64 {
//	    return runtime.resolveForwardedRecvFieldMask(
//	        carrier,
//	        <fn.GdForwarder.FieldOffset>,    // typed uintptr literal
//	        <fn.GdForwarder.MethodIdx>,      // typed int literal
//	        heapMask,
//	        depth,
//	    )
//	}
//
// The wrapper's signature & receiver type are NOT used inside
// the synthesized fn; the runtime helper does the cast via
// pointer arithmetic with the supplied fieldOffset.
func buildForwarderComputeFn(wrapper *ir.Func, name string) *ir.Func {
	pos := base.AutogeneratedPos
	if wrapper.Pos().IsKnown() {
		pos = wrapper.Pos()
	}

	unsafePtr := types.Types[types.TUNSAFEPTR]
	u64 := types.Types[types.TUINT64]
	intT := types.Types[types.TINT]
	uintptrT := types.Types[types.TUINTPTR]

	// Param symbols. Use named params (carrier/heapMask/depth)
	// rather than blanks so DWARF + escape analysis don't choke.
	carrierSym := typecheck.Lookup("carrier")
	heapMaskSym := typecheck.Lookup("heapMask")
	depthSym := typecheck.Lookup("depth")

	sig := types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, carrierSym, unsafePtr),
			types.NewField(pos, heapMaskSym, u64),
			types.NewField(pos, depthSym, intT),
		},
		[]*types.Field{
			types.NewField(pos, nil, u64),
		})

	// Stable mangled name (passed in from the registry). The
	// wrapper's linksym carries the receiver type prefix so the
	// caller can build a unique name even when two types in the
	// same package share an unqualified method name.
	sym := wrapper.Sym().Pkg.Lookup(name)
	if sym.Def != nil {
		// Already synthesised earlier in the build. Reuse.
		if n, ok := sym.Def.(*ir.Name); ok && n.Func != nil {
			return n.Func
		}
	}
	fn := ir.NewFunc(pos, pos, sym, sig)
	sym.Def = fn.Nname
	fn.SetDupok(true)

	typecheck.DeclFunc(fn)
	carrier := fn.Dcl[0]
	heapMask := fn.Dcl[1]
	depth := fn.Dcl[2]

	// runtime.resolveForwardedRecvFieldMask(carrier, fieldOffset, methodIdx, heapMask, depth)
	helper := typecheck.LookupRuntime("resolveForwardedRecvFieldMask")

	fieldOffset := uintptrLit(pos, wrapper.GdForwarder.FieldOffset)
	methodIdx := intLit(pos, int64(wrapper.GdForwarder.MethodIdx))

	call := ir.NewCallExpr(pos, ir.OCALL, helper, []ir.Node{
		carrier,
		fieldOffset,
		methodIdx,
		heapMask,
		depth,
	})

	ret := ir.NewReturnStmt(pos, []ir.Node{call})
	fn.Body = []ir.Node{ret}

	typecheck.FinishFuncBody()

	ir.WithFunc(fn, func() {
		typecheck.Stmts(fn.Body)
	})

	// Use depth so the unused-import gate (if any) doesn't fire
	// for the cast helpers below.
	_ = uintptrT

	return fn
}

// uintptrLit / intLit produce typed-literal Nodes the synthesizer
// uses for the helper's compile-time constant args. Mirrors the
// helpers walk uses for its open-coded mask resolution.
func uintptrLit(pos src.XPos, v int64) ir.Node {
	n := ir.NewInt(pos, v)
	n.SetType(types.Types[types.TUINTPTR])
	n.SetTypecheck(1)
	return n
}

func intLit(pos src.XPos, v int64) ir.Node {
	n := ir.NewInt(pos, v)
	n.SetType(types.Types[types.TINT])
	n.SetTypecheck(1)
	return n
}
