// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pkginit

import (
	"cmd/compile/internal/base"
	"cmd/compile/internal/ir"
	"cmd/compile/internal/noder"
	"cmd/compile/internal/objw"
	"cmd/compile/internal/staticinit"
	"cmd/compile/internal/typecheck"
	"cmd/compile/internal/types"
	"cmd/internal/obj"
	"cmd/internal/objabi"
	"cmd/internal/src"
)

// MakeTask makes an initialization record for the package, if necessary.
// See runtime/proc.go:initTask for its layout.
// The 3 tasks for initialization are:
//  1. Initialize all of the packages the current package depends on.
//  2. Initialize all the variables that have initializers.
//  3. Run any init functions.
func MakeTask(gd *base.Invocation) {
	var deps []*obj.LSym // initTask records for packages the current package depends on
	var fns []*obj.LSym  // functions to call for package initialization

	// Find imported packages with init tasks.
	for _, pkg := range typecheck.Target(gd).Imports {
		n, ok := pkg.Lookup(".inittask").Def.(*ir.Name)
		if !ok {
			continue
		}
		if n.Op() != ir.ONAME || n.Class != ir.PEXTERN {
			gd.Fatalf("bad inittask: %v", n)
		}
		deps = append(deps, n.Linksym())
	}
	if gd.Flag.ASan {
		// Make an initialization function to call runtime.asanregisterglobals to register an
		// array of instrumented global variables when -asan is enabled. An instrumented global
		// variable is described by a structure.
		// See the _asan_global structure declared in src/runtime/asan/asan.go.
		//
		// func init {
		// 		var globals []_asan_global {...}
		// 		asanregisterglobals(&globals[0], len(globals))
		// }
		for _, n := range typecheck.Target(gd).Externs {
			if canInstrumentGlobal(gd, n) {
				name := n.Sym().Name
				InstrumentGlobalsMap[name] = n
				InstrumentGlobalsSlice = append(InstrumentGlobalsSlice, n)
			}
		}
		ni := len(InstrumentGlobalsMap)
		if ni != 0 {
			// Make an init._ function.
			pos := gd.AutogeneratedPos
			gd.Pos = pos

			sym := noder.Renameinit(gd)
			fnInit := ir.NewFunc(gd, pos, pos, sym, types.NewSignature(gd, nil, nil, nil))
			typecheck.DeclFunc(gd, fnInit)

			// Get an array of instrumented global variables.
			globals := instrumentGlobals(gd, fnInit)

			// Call runtime.asanregisterglobals function to poison redzones.
			// runtime.asanregisterglobals(unsafe.Pointer(&globals[0]), ni)
			asancall := ir.NewCallExpr(gd, gd.Pos, ir.OCALL, typecheck.LookupRuntime(gd, "asanregisterglobals"), nil)
			asancall.Args.Append(typecheck.ConvNop(gd, typecheck.NodAddr(gd,
				ir.NewIndexExpr(gd, gd.Pos, globals, ir.NewInt(gd, gd.Pos, 0))), types.Types[types.TUNSAFEPTR]))
			asancall.Args.Append(typecheck.DefaultLit(gd, ir.NewInt(gd, gd.Pos, int64(ni)), types.Types[types.TUINTPTR]))

			fnInit.Body.Append(asancall)
			typecheck.FinishFuncBody(gd)
			gd.CurFunc = fnInit
			typecheck.Stmts(gd, fnInit.Body)
			gd.CurFunc = nil

			typecheck.Target(gd).Inits = append(typecheck.Target(gd).Inits, fnInit)
		}
	}

	// Record user init functions.
	for _, fn := range typecheck.Target(gd).Inits {
		if fn.Sym().Name == "init" {
			// Synthetic init function for initialization of package-scope
			// variables. We can use staticinit to optimize away static
			// assignments.
			s := staticinit.Schedule{
				Plans: make(map[ir.Node]*staticinit.Plan),
				Temps: make(map[ir.Node]*ir.Name),
			}
			for _, n := range fn.Body {
				s.StaticInit(gd, n)
			}
			fn.Body = s.Out
			ir.WithFunc(gd, fn, func() {
				typecheck.Stmts(gd, fn.Body)
			})

			if len(fn.Body) == 0 {
				fn.Body = []ir.Node{ir.NewBlockStmt(gd, src.NoXPos, nil)}
			}
		}

		// Skip init functions with empty bodies.
		if len(fn.Body) == 1 {
			if stmt := fn.Body[0]; stmt.Op() == ir.OBLOCK && len(stmt.(*ir.BlockStmt).List) == 0 {
				continue
			}
		}
		fns = append(fns, fn.Nname.Linksym())
	}

	if len(deps) == 0 && len(fns) == 0 && types.LocalPkg(gd).Path != "main" && types.LocalPkg(gd).Path != "runtime" {
		return // nothing to initialize
	}

	// Make an .inittask structure.
	sym := typecheck.Lookup(gd, ".inittask")
	task := ir.NewNameAt(gd, gd.Pos, sym, types.Types[types.TUINT8]) // fake type
	task.Class = ir.PEXTERN
	sym.Def = task
	lsym := task.Linksym()
	ot := 0
	ot = objw.Uint32(gd, lsym, ot, 0) // state: not initialized yet
	ot = objw.Uint32(gd, lsym, ot, uint32(len(fns)))
	for _, f := range fns {
		ot = objw.SymPtr(gd, lsym, ot, f, 0)
	}

	// Add relocations which tell the linker all of the packages
	// that this package depends on (and thus, all of the packages
	// that need to be initialized before this one).
	for _, d := range deps {
		lsym.AddRel(gd.Ctxt, obj.Reloc{Type: objabi.R_INITORDER, Sym: d})
	}
	// An initTask has pointers, but none into the Go heap.
	// It's not quite read only, the state field must be modifiable.
	objw.Global(gd, lsym, int32(ot), obj.NOPTR)
}
