// Code generated by mkbuiltin.go. DO NOT EDIT.

package typecheck

import (
	"cmd/compile/internal/types"
	"cmd/internal/src"
)

// Not inlining this function removes a significant chunk of init code.
//
//go:noinline
func newSig(params, results []*types.Field) *types.Type {
	return types.NewSignature(nil, params, results)
}

func params(tlist ...*types.Type) []*types.Field {
	flist := make([]*types.Field, len(tlist))
	for i, typ := range tlist {
		flist[i] = types.NewField(src.NoXPos, nil, typ)
	}
	return flist
}

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"mallocgc", funcTag, 8},
	{"panicdivide", funcTag, 9},
	{"panicshift", funcTag, 9},
	{"panicmakeslicelen", funcTag, 9},
	{"panicmakeslicecap", funcTag, 9},
	{"throwinit", funcTag, 9},
	{"panicwrap", funcTag, 9},
	{"gopanic", funcTag, 11},
	{"gorecover", funcTag, 12},
	{"goschedguarded", funcTag, 9},
	{"goPanicIndex", funcTag, 14},
	{"goPanicIndexU", funcTag, 16},
	{"goPanicSliceAlen", funcTag, 14},
	{"goPanicSliceAlenU", funcTag, 16},
	{"goPanicSliceAcap", funcTag, 14},
	{"goPanicSliceAcapU", funcTag, 16},
	{"goPanicSliceB", funcTag, 14},
	{"goPanicSliceBU", funcTag, 16},
	{"goPanicSlice3Alen", funcTag, 14},
	{"goPanicSlice3AlenU", funcTag, 16},
	{"goPanicSlice3Acap", funcTag, 14},
	{"goPanicSlice3AcapU", funcTag, 16},
	{"goPanicSlice3B", funcTag, 14},
	{"goPanicSlice3BU", funcTag, 16},
	{"goPanicSlice3C", funcTag, 14},
	{"goPanicSlice3CU", funcTag, 16},
	{"goPanicSliceConvert", funcTag, 14},
	{"printbool", funcTag, 17},
	{"printfloat64", funcTag, 19},
	{"printfloat32", funcTag, 21},
	{"printint", funcTag, 23},
	{"printhex", funcTag, 25},
	{"printuint", funcTag, 25},
	{"printcomplex128", funcTag, 27},
	{"printcomplex64", funcTag, 29},
	{"printstring", funcTag, 31},
	{"printquoted", funcTag, 31},
	{"printpointer", funcTag, 32},
	{"printuintptr", funcTag, 33},
	{"printiface", funcTag, 32},
	{"printeface", funcTag, 32},
	{"printslice", funcTag, 32},
	{"printnl", funcTag, 9},
	{"printsp", funcTag, 9},
	{"printlock", funcTag, 9},
	{"printunlock", funcTag, 9},
	{"concatstring2", funcTag, 36},
	{"concatstring3", funcTag, 37},
	{"concatstring4", funcTag, 38},
	{"concatstring5", funcTag, 39},
	{"concatstrings", funcTag, 41},
	{"concatbyte2", funcTag, 43},
	{"concatbyte3", funcTag, 44},
	{"concatbyte4", funcTag, 45},
	{"concatbyte5", funcTag, 46},
	{"concatbytes", funcTag, 47},
	{"cmpstring", funcTag, 48},
	{"sliceinlinestring", funcTag, 49},
	{"stringDataHeap", funcTag, 50},
	{"stringcopy", funcTag, 51},
	{"intstring", funcTag, 54},
	{"slicebytetostring", funcTag, 55},
	{"slicebytetostringtmp", funcTag, 56},
	{"slicerunetostring", funcTag, 59},
	{"stringtoslicebyte", funcTag, 60},
	{"stringtoslicerune", funcTag, 63},
	{"slicecopy", funcTag, 64},
	{"decoderune", funcTag, 65},
	{"countrunes", funcTag, 66},
	{"convT", funcTag, 67},
	{"convTnoptr", funcTag, 67},
	{"materializeToHeap", funcTag, 68},
	{"maybeEscapeArg", funcTag, 69},
	{"maybeEscapeClosureArg", funcTag, 70},
	{"maybeEscapeIfaceArg", funcTag, 71},
	{"maybeInPlace", funcTag, 68},
	{"convT16", funcTag, 73},
	{"convT32", funcTag, 75},
	{"convT64", funcTag, 76},
	{"convTstring", funcTag, 77},
	{"convTslice", funcTag, 80},
	{"assertE2I", funcTag, 81},
	{"assertE2I2", funcTag, 81},
	{"panicdottypeE", funcTag, 82},
	{"panicdottypeI", funcTag, 82},
	{"panicnildottype", funcTag, 83},
	{"typeAssert", funcTag, 81},
	{"interfaceSwitch", funcTag, 84},
	{"ifaceeq", funcTag, 86},
	{"efaceeq", funcTag, 86},
	{"panicrangestate", funcTag, 87},
	{"deferrangefunc", funcTag, 12},
	{"rand", funcTag, 88},
	{"rand32", funcTag, 89},
	{"makemap64", funcTag, 91},
	{"makemap", funcTag, 92},
	{"makemap_small", funcTag, 93},
	{"mapaccess1", funcTag, 94},
	{"mapaccess1_fast32", funcTag, 95},
	{"mapaccess1_fast64", funcTag, 96},
	{"mapaccess1_faststr", funcTag, 97},
	{"mapaccess1_fat", funcTag, 98},
	{"mapaccess2", funcTag, 99},
	{"mapaccess2_fast32", funcTag, 100},
	{"mapaccess2_fast64", funcTag, 101},
	{"mapaccess2_faststr", funcTag, 102},
	{"mapaccess2_fat", funcTag, 103},
	{"mapassign", funcTag, 94},
	{"mapassign_fast32", funcTag, 95},
	{"mapassign_fast32ptr", funcTag, 104},
	{"mapassign_fast64", funcTag, 96},
	{"mapassign_fast64ptr", funcTag, 104},
	{"mapassign_faststr", funcTag, 97},
	{"mapIterStart", funcTag, 105},
	{"mapdelete", funcTag, 105},
	{"mapdelete_fast32", funcTag, 106},
	{"mapdelete_fast64", funcTag, 107},
	{"mapdelete_faststr", funcTag, 108},
	{"mapIterNext", funcTag, 109},
	{"mapclear", funcTag, 110},
	{"makechan64", funcTag, 112},
	{"makechan", funcTag, 113},
	{"chanrecv1", funcTag, 115},
	{"chanrecv2", funcTag, 116},
	{"chansend1", funcTag, 118},
	{"closechan", funcTag, 119},
	{"chanlen", funcTag, 120},
	{"chancap", funcTag, 120},
	{"writeBarrier", varTag, 122},
	{"typedmemmove", funcTag, 123},
	{"typedmemclr", funcTag, 124},
	{"typedslicecopy", funcTag, 125},
	{"selectnbsend", funcTag, 126},
	{"selectnbrecv", funcTag, 127},
	{"selectsetpc", funcTag, 128},
	{"selectgo", funcTag, 129},
	{"block", funcTag, 9},
	{"makeslice", funcTag, 130},
	{"makeslice64", funcTag, 131},
	{"makeslicecopy", funcTag, 132},
	{"growslice", funcTag, 134},
	{"growsliceBuf", funcTag, 135},
	{"growsliceBufNoAlias", funcTag, 135},
	{"growsliceNoAlias", funcTag, 134},
	{"unsafeslicecheckptr", funcTag, 136},
	{"panicunsafeslicelen", funcTag, 9},
	{"panicunsafeslicenilptr", funcTag, 9},
	{"unsafestringcheckptr", funcTag, 137},
	{"panicunsafestringlen", funcTag, 9},
	{"panicunsafestringnilptr", funcTag, 9},
	{"moveSlice", funcTag, 138},
	{"moveSliceNoScan", funcTag, 139},
	{"moveSliceNoCap", funcTag, 140},
	{"moveSliceNoCapNoScan", funcTag, 141},
	{"memmove", funcTag, 142},
	{"memclrNoHeapPointers", funcTag, 143},
	{"memclrHasPointers", funcTag, 143},
	{"memequal", funcTag, 144},
	{"memequal0", funcTag, 145},
	{"memequal8", funcTag, 145},
	{"memequal16", funcTag, 145},
	{"memequal32", funcTag, 145},
	{"memequal64", funcTag, 145},
	{"memequal128", funcTag, 145},
	{"f32equal", funcTag, 146},
	{"f64equal", funcTag, 146},
	{"c64equal", funcTag, 146},
	{"c128equal", funcTag, 146},
	{"strequal", funcTag, 146},
	{"streqfast", funcTag, 147},
	{"interequal", funcTag, 146},
	{"nilinterequal", funcTag, 146},
	{"memhash", funcTag, 148},
	{"memhash0", funcTag, 149},
	{"memhash8", funcTag, 149},
	{"memhash16", funcTag, 149},
	{"memhash32", funcTag, 149},
	{"memhash64", funcTag, 149},
	{"memhash128", funcTag, 149},
	{"f32hash", funcTag, 150},
	{"f64hash", funcTag, 150},
	{"c64hash", funcTag, 150},
	{"c128hash", funcTag, 150},
	{"strhash", funcTag, 150},
	{"interhash", funcTag, 150},
	{"nilinterhash", funcTag, 150},
	{"int64div", funcTag, 151},
	{"uint64div", funcTag, 152},
	{"int64mod", funcTag, 151},
	{"uint64mod", funcTag, 152},
	{"float64toint64", funcTag, 153},
	{"float64touint64", funcTag, 154},
	{"float64touint32", funcTag, 155},
	{"int64tofloat64", funcTag, 156},
	{"int64tofloat32", funcTag, 157},
	{"uint64tofloat64", funcTag, 158},
	{"uint64tofloat32", funcTag, 159},
	{"uint32tofloat64", funcTag, 160},
	{"complex128div", funcTag, 161},
	{"racefuncenter", funcTag, 33},
	{"racefuncexit", funcTag, 9},
	{"raceread", funcTag, 33},
	{"racewrite", funcTag, 33},
	{"racereadrange", funcTag, 162},
	{"racewriterange", funcTag, 162},
	{"msanread", funcTag, 162},
	{"msanwrite", funcTag, 162},
	{"msanmove", funcTag, 163},
	{"asanread", funcTag, 162},
	{"asanwrite", funcTag, 162},
	{"checkptrAlignment", funcTag, 164},
	{"checkptrArithmetic", funcTag, 166},
	{"libfuzzerTraceCmp1", funcTag, 167},
	{"libfuzzerTraceCmp2", funcTag, 168},
	{"libfuzzerTraceCmp4", funcTag, 169},
	{"libfuzzerTraceCmp8", funcTag, 170},
	{"libfuzzerTraceConstCmp1", funcTag, 167},
	{"libfuzzerTraceConstCmp2", funcTag, 168},
	{"libfuzzerTraceConstCmp4", funcTag, 169},
	{"libfuzzerTraceConstCmp8", funcTag, 170},
	{"libfuzzerHookStrCmp", funcTag, 171},
	{"libfuzzerHookEqualFold", funcTag, 171},
	{"addCovMeta", funcTag, 173},
	{"x86HasAVX", varTag, 6},
	{"x86HasFMA", varTag, 6},
	{"x86HasPOPCNT", varTag, 6},
	{"x86HasSSE41", varTag, 6},
	{"armHasVFPv4", varTag, 6},
	{"arm64HasATOMICS", varTag, 6},
	{"loong64HasLAMCAS", varTag, 6},
	{"loong64HasLAM_BH", varTag, 6},
	{"loong64HasLSX", varTag, 6},
	{"riscv64HasZbb", varTag, 6},
	{"asanregisterglobals", funcTag, 143},
	{"KeepAlive", funcTag, 11},
}

func runtimeTypes() []*types.Type {
	var typs [174]*types.Type
	typs[0] = types.ByteType
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[types.TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = newSig(params(typs[1]), params(typs[3]))
	typs[5] = types.Types[types.TUINTPTR]
	typs[6] = types.Types[types.TBOOL]
	typs[7] = types.Types[types.TUNSAFEPTR]
	typs[8] = newSig(params(typs[5], typs[1], typs[6]), params(typs[7]))
	typs[9] = newSig(nil, nil)
	typs[10] = types.Types[types.TINTER]
	typs[11] = newSig(params(typs[10]), nil)
	typs[12] = newSig(nil, params(typs[10]))
	typs[13] = types.Types[types.TINT]
	typs[14] = newSig(params(typs[13], typs[13]), nil)
	typs[15] = types.Types[types.TUINT]
	typs[16] = newSig(params(typs[15], typs[13]), nil)
	typs[17] = newSig(params(typs[6]), nil)
	typs[18] = types.Types[types.TFLOAT64]
	typs[19] = newSig(params(typs[18]), nil)
	typs[20] = types.Types[types.TFLOAT32]
	typs[21] = newSig(params(typs[20]), nil)
	typs[22] = types.Types[types.TINT64]
	typs[23] = newSig(params(typs[22]), nil)
	typs[24] = types.Types[types.TUINT64]
	typs[25] = newSig(params(typs[24]), nil)
	typs[26] = types.Types[types.TCOMPLEX128]
	typs[27] = newSig(params(typs[26]), nil)
	typs[28] = types.Types[types.TCOMPLEX64]
	typs[29] = newSig(params(typs[28]), nil)
	typs[30] = types.Types[types.TSTRING]
	typs[31] = newSig(params(typs[30]), nil)
	typs[32] = newSig(params(typs[2]), nil)
	typs[33] = newSig(params(typs[5]), nil)
	typs[34] = types.NewArray(typs[0], 32)
	typs[35] = types.NewPtr(typs[34])
	typs[36] = newSig(params(typs[35], typs[30], typs[30]), params(typs[30]))
	typs[37] = newSig(params(typs[35], typs[30], typs[30], typs[30]), params(typs[30]))
	typs[38] = newSig(params(typs[35], typs[30], typs[30], typs[30], typs[30]), params(typs[30]))
	typs[39] = newSig(params(typs[35], typs[30], typs[30], typs[30], typs[30], typs[30]), params(typs[30]))
	typs[40] = types.NewSlice(typs[30])
	typs[41] = newSig(params(typs[35], typs[40]), params(typs[30]))
	typs[42] = types.NewSlice(typs[0])
	typs[43] = newSig(params(typs[35], typs[30], typs[30]), params(typs[42]))
	typs[44] = newSig(params(typs[35], typs[30], typs[30], typs[30]), params(typs[42]))
	typs[45] = newSig(params(typs[35], typs[30], typs[30], typs[30], typs[30]), params(typs[42]))
	typs[46] = newSig(params(typs[35], typs[30], typs[30], typs[30], typs[30], typs[30]), params(typs[42]))
	typs[47] = newSig(params(typs[35], typs[40]), params(typs[42]))
	typs[48] = newSig(params(typs[30], typs[30]), params(typs[13]))
	typs[49] = newSig(params(typs[30], typs[13], typs[13]), params(typs[30]))
	typs[50] = newSig(params(typs[30]), params(typs[1]))
	typs[51] = newSig(params(typs[1], typs[13], typs[30]), params(typs[13]))
	typs[52] = types.NewArray(typs[0], 4)
	typs[53] = types.NewPtr(typs[52])
	typs[54] = newSig(params(typs[53], typs[22]), params(typs[30]))
	typs[55] = newSig(params(typs[35], typs[1], typs[13]), params(typs[30]))
	typs[56] = newSig(params(typs[1], typs[13]), params(typs[30]))
	typs[57] = types.RuneType
	typs[58] = types.NewSlice(typs[57])
	typs[59] = newSig(params(typs[35], typs[58]), params(typs[30]))
	typs[60] = newSig(params(typs[35], typs[30]), params(typs[42]))
	typs[61] = types.NewArray(typs[57], 32)
	typs[62] = types.NewPtr(typs[61])
	typs[63] = newSig(params(typs[62], typs[30]), params(typs[58]))
	typs[64] = newSig(params(typs[3], typs[13], typs[3], typs[13], typs[5]), params(typs[13]))
	typs[65] = newSig(params(typs[30], typs[13]), params(typs[57], typs[13]))
	typs[66] = newSig(params(typs[30]), params(typs[13]))
	typs[67] = newSig(params(typs[1], typs[3]), params(typs[7]))
	typs[68] = newSig(params(typs[7], typs[1]), params(typs[7]))
	typs[69] = newSig(params(typs[24], typs[13], typs[7], typs[1]), params(typs[7]))
	typs[70] = newSig(params(typs[7], typs[13], typs[7], typs[1]), params(typs[7]))
	typs[71] = newSig(params(typs[7], typs[13], typs[13], typs[7], typs[1]), params(typs[7]))
	typs[72] = types.Types[types.TUINT16]
	typs[73] = newSig(params(typs[72]), params(typs[7]))
	typs[74] = types.Types[types.TUINT32]
	typs[75] = newSig(params(typs[74]), params(typs[7]))
	typs[76] = newSig(params(typs[24]), params(typs[7]))
	typs[77] = newSig(params(typs[30]), params(typs[7]))
	typs[78] = types.Types[types.TUINT8]
	typs[79] = types.NewSlice(typs[78])
	typs[80] = newSig(params(typs[79]), params(typs[7]))
	typs[81] = newSig(params(typs[1], typs[1]), params(typs[1]))
	typs[82] = newSig(params(typs[1], typs[1], typs[1]), nil)
	typs[83] = newSig(params(typs[1]), nil)
	typs[84] = newSig(params(typs[1], typs[1]), params(typs[13], typs[1]))
	typs[85] = types.NewPtr(typs[5])
	typs[86] = newSig(params(typs[85], typs[7], typs[7]), params(typs[6]))
	typs[87] = newSig(params(typs[13]), nil)
	typs[88] = newSig(nil, params(typs[24]))
	typs[89] = newSig(nil, params(typs[74]))
	typs[90] = types.NewMap(typs[2], typs[2])
	typs[91] = newSig(params(typs[1], typs[22], typs[3]), params(typs[90]))
	typs[92] = newSig(params(typs[1], typs[13], typs[3]), params(typs[90]))
	typs[93] = newSig(nil, params(typs[90]))
	typs[94] = newSig(params(typs[1], typs[90], typs[3]), params(typs[3]))
	typs[95] = newSig(params(typs[1], typs[90], typs[74]), params(typs[3]))
	typs[96] = newSig(params(typs[1], typs[90], typs[24]), params(typs[3]))
	typs[97] = newSig(params(typs[1], typs[90], typs[30]), params(typs[3]))
	typs[98] = newSig(params(typs[1], typs[90], typs[3], typs[1]), params(typs[3]))
	typs[99] = newSig(params(typs[1], typs[90], typs[3]), params(typs[3], typs[6]))
	typs[100] = newSig(params(typs[1], typs[90], typs[74]), params(typs[3], typs[6]))
	typs[101] = newSig(params(typs[1], typs[90], typs[24]), params(typs[3], typs[6]))
	typs[102] = newSig(params(typs[1], typs[90], typs[30]), params(typs[3], typs[6]))
	typs[103] = newSig(params(typs[1], typs[90], typs[3], typs[1]), params(typs[3], typs[6]))
	typs[104] = newSig(params(typs[1], typs[90], typs[7]), params(typs[3]))
	typs[105] = newSig(params(typs[1], typs[90], typs[3]), nil)
	typs[106] = newSig(params(typs[1], typs[90], typs[74]), nil)
	typs[107] = newSig(params(typs[1], typs[90], typs[24]), nil)
	typs[108] = newSig(params(typs[1], typs[90], typs[30]), nil)
	typs[109] = newSig(params(typs[3]), nil)
	typs[110] = newSig(params(typs[1], typs[90]), nil)
	typs[111] = types.NewChan(typs[2], types.Cboth)
	typs[112] = newSig(params(typs[1], typs[22]), params(typs[111]))
	typs[113] = newSig(params(typs[1], typs[13]), params(typs[111]))
	typs[114] = types.NewChan(typs[2], types.Crecv)
	typs[115] = newSig(params(typs[114], typs[3]), nil)
	typs[116] = newSig(params(typs[114], typs[3]), params(typs[6]))
	typs[117] = types.NewChan(typs[2], types.Csend)
	typs[118] = newSig(params(typs[117], typs[3]), nil)
	typs[119] = newSig(params(typs[117]), nil)
	typs[120] = newSig(params(typs[2]), params(typs[13]))
	typs[121] = types.NewArray(typs[0], 3)
	typs[122] = types.NewStruct([]*types.Field{types.NewField(src.NoXPos, Lookup("enabled"), typs[6]), types.NewField(src.NoXPos, Lookup("pad"), typs[121]), types.NewField(src.NoXPos, Lookup("cgo"), typs[6]), types.NewField(src.NoXPos, Lookup("alignme"), typs[24])})
	typs[123] = newSig(params(typs[1], typs[3], typs[3]), nil)
	typs[124] = newSig(params(typs[1], typs[3]), nil)
	typs[125] = newSig(params(typs[1], typs[3], typs[13], typs[3], typs[13]), params(typs[13]))
	typs[126] = newSig(params(typs[117], typs[3]), params(typs[6]))
	typs[127] = newSig(params(typs[3], typs[114]), params(typs[6], typs[6]))
	typs[128] = newSig(params(typs[85]), nil)
	typs[129] = newSig(params(typs[1], typs[1], typs[85], typs[13], typs[13], typs[6]), params(typs[13], typs[6]))
	typs[130] = newSig(params(typs[1], typs[13], typs[13]), params(typs[7]))
	typs[131] = newSig(params(typs[1], typs[22], typs[22]), params(typs[7]))
	typs[132] = newSig(params(typs[1], typs[13], typs[13], typs[7]), params(typs[7]))
	typs[133] = types.NewSlice(typs[2])
	typs[134] = newSig(params(typs[3], typs[13], typs[13], typs[13], typs[1]), params(typs[133]))
	typs[135] = newSig(params(typs[3], typs[13], typs[13], typs[13], typs[1], typs[3], typs[13]), params(typs[133]))
	typs[136] = newSig(params(typs[1], typs[7], typs[22]), nil)
	typs[137] = newSig(params(typs[7], typs[22]), nil)
	typs[138] = newSig(params(typs[1], typs[1], typs[13], typs[13]), params(typs[1], typs[13], typs[13]))
	typs[139] = newSig(params(typs[5], typs[1], typs[13], typs[13]), params(typs[1], typs[13], typs[13]))
	typs[140] = newSig(params(typs[1], typs[1], typs[13]), params(typs[1], typs[13], typs[13]))
	typs[141] = newSig(params(typs[5], typs[1], typs[13]), params(typs[1], typs[13], typs[13]))
	typs[142] = newSig(params(typs[3], typs[3], typs[5]), nil)
	typs[143] = newSig(params(typs[7], typs[5]), nil)
	typs[144] = newSig(params(typs[3], typs[3], typs[5]), params(typs[6]))
	typs[145] = newSig(params(typs[3], typs[3]), params(typs[6]))
	typs[146] = newSig(params(typs[7], typs[7]), params(typs[6]))
	typs[147] = newSig(params(typs[30], typs[30]), params(typs[6]))
	typs[148] = newSig(params(typs[3], typs[5], typs[5]), params(typs[5]))
	typs[149] = newSig(params(typs[7], typs[5]), params(typs[5]))
	typs[150] = newSig(params(typs[3], typs[5]), params(typs[5]))
	typs[151] = newSig(params(typs[22], typs[22]), params(typs[22]))
	typs[152] = newSig(params(typs[24], typs[24]), params(typs[24]))
	typs[153] = newSig(params(typs[18]), params(typs[22]))
	typs[154] = newSig(params(typs[18]), params(typs[24]))
	typs[155] = newSig(params(typs[18]), params(typs[74]))
	typs[156] = newSig(params(typs[22]), params(typs[18]))
	typs[157] = newSig(params(typs[22]), params(typs[20]))
	typs[158] = newSig(params(typs[24]), params(typs[18]))
	typs[159] = newSig(params(typs[24]), params(typs[20]))
	typs[160] = newSig(params(typs[74]), params(typs[18]))
	typs[161] = newSig(params(typs[26], typs[26]), params(typs[26]))
	typs[162] = newSig(params(typs[5], typs[5]), nil)
	typs[163] = newSig(params(typs[5], typs[5], typs[5]), nil)
	typs[164] = newSig(params(typs[7], typs[1], typs[5]), nil)
	typs[165] = types.NewSlice(typs[7])
	typs[166] = newSig(params(typs[7], typs[165]), nil)
	typs[167] = newSig(params(typs[78], typs[78], typs[15]), nil)
	typs[168] = newSig(params(typs[72], typs[72], typs[15]), nil)
	typs[169] = newSig(params(typs[74], typs[74], typs[15]), nil)
	typs[170] = newSig(params(typs[24], typs[24], typs[15]), nil)
	typs[171] = newSig(params(typs[30], typs[30], typs[15]), nil)
	typs[172] = types.NewArray(typs[0], 16)
	typs[173] = newSig(params(typs[7], typs[74], typs[172], typs[30], typs[13], typs[78], typs[78]), params(typs[74]))
	return typs[:]
}

var coverageDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"initHook", funcTag, 1},
}

func coverageTypes() []*types.Type {
	var typs [2]*types.Type
	typs[0] = types.Types[types.TBOOL]
	typs[1] = newSig(params(typs[0]), nil)
	return typs[:]
}
