// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package base

import (
	"cmd/internal/obj"
	"cmd/internal/src"
)

type Invocation struct {
	atExitFuncs []func()

	Timer Timings

	// Debug holds the parsed debugging configuration values.
	Debug DebugFlags

	// DebugSSA is called to set a -d ssa/... option.
	// If nil, those options are reported as invalid options.
	// If DebugSSA returns a non-empty string, that text is reported as a compiler error.
	DebugSSA func(phase, flag string, val int, valString string) string

	Ctxt *obj.Link

	// Pos is the current source position being processed,
	// printed by Errorf, ErrorfLang, Fatalf, and Warnf.
	Pos src.XPos

	AutogeneratedPos src.XPos

	// Flag holds the parsed command-line flags.
	// See ParseFlag for non-zero defaults.
	Flag CmdFlags

	errorMsgs       []errorMsg
	numErrors       int // number of entries in errorMsgs that are errors (as opposed to warnings)
	numSyntaxErrors int

	// lasterror keeps track of the most recently issued error,
	// to avoid printing multiple error messages on the same line.
	lasterror struct {
		syntax src.XPos // source position of last syntax error
		other  src.XPos // source position of last non-syntax error
		msg    string   // error message of last non-syntax error
	}

	CurFunc any // *ir.Func
	Package any //*ir.Package

	LocalPkg any // *types.Pkg

	Status int

	// Per-compile counters used to mint unique synthesised names.
	// Were package-level globals; threaded here so multiple compile
	// invocations in one process don't share name spaces.
	Renameinitgen     int   // noder/noder.go (renameinit name minter)
	NoderInlgen       int   // noder/reader.go (inlined-call name minter)
	Dnamecount        int   // reflectdata/reflect.go (dname name minter)
	Slicedatagen      int   // staticdata/data.go (sliceData name minter)
	Statuniqgen       int   // staticinit/sched.go (static temp name minter)
	Mapinitgen        int   // staticinit/sched.go (map-init name minter)
	TypeAssertGen     int   // walk/expr.go (type-assert helper minter)
	InterfaceSwitchGen int  // walk/switch.go (iface-switch helper minter)
	GlobClosgen       int32 // ir/func.go (closure name minter)

	// Per-compile noder reader maps. Type-asserted at use site to
	// avoid an import cycle (noder imports base, not the other
	// direction). Were package-level globals; same per-Invocation
	// rationale as the counters above.
	NoderObjReader        any // map[*types.Sym]noder.pkgReaderIndex
	NoderBodyReader       any // map[*ir.Func]noder.pkgReaderIndex
	NoderImportBodyReader any // map[*types.Sym]noder.pkgReaderIndex
}
