// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package base

import (
	"cmd/internal/obj"
	"cmd/internal/src"
	"flag"
	"io"
	"sync"
)

type Invocation struct {
	atExitFuncs []func()

	// InProcess is set by cmd/compile/host.Run for invocations driven
	// in-process from cmd/go. It gates process-wide tweaks that are
	// safe in a standalone compile but harmful when many compiles
	// share one process — most importantly AdjustStartingHeap, which
	// calls debug.SetGCPercent(big) to delay GC until the heap reaches
	// ~128 MB. Standalone compiles exit and free everything; in-process
	// compiles all leave GOGC cranked up at once and cmd/go's RSS
	// climbs without bound until the kernel SIGKILLs it.
	InProcess bool

	// Stderr is where Errorf / FlushErrors / Fatalf write diagnostics.
	// Standalone compile (cmd/compile/main.go) leaves this nil and we
	// fall back to os.Stderr. cmd/compile/host.Run sets it to the
	// stderr writer cmd/go provided so each in-process invocation's
	// diagnostics go through cmd/go's reportCmd (cgo error translation,
	// build-output JSON capture for `go test -json`, etc.) instead of
	// leaking onto cmd/go's own os.Stderr.
	Stderr io.Writer

	// Flagset is the per-Invocation flag set used by registerFlags
	// and ParseFlags. Each Invocation owns its own *flag.FlagSet so
	// multiple compile invocations in the same process don't fight
	// over flag.CommandLine. Lazy-initialised by ParseFlags when
	// nil, so callers that don't supply one (cmd/compile/main.go)
	// keep working unchanged.
	Flagset *flag.FlagSet

	Timer Timings

	// Debug holds the parsed debugging configuration values.
	Debug DebugFlags

	// DebugSSA is called to set a -d ssa/... option.
	// If nil, those options are reported as invalid options.
	// If DebugSSA returns a non-empty string, that text is reported as a compiler error.
	DebugSSA func(phase, flag string, val int, valString string) string

	Ctxt *obj.Link

	// Pos is the current source position being processed,
	// printed by Errorf, ErrorfLang, Fatalf, and Warnf.
	Pos src.XPos

	AutogeneratedPos src.XPos

	// Flag holds the parsed command-line flags.
	// See ParseFlag for non-zero defaults.
	Flag CmdFlags

	errorMsgs       []errorMsg
	numErrors       int // number of entries in errorMsgs that are errors (as opposed to warnings)
	numSyntaxErrors int

	// lasterror keeps track of the most recently issued error,
	// to avoid printing multiple error messages on the same line.
	lasterror struct {
		syntax src.XPos // source position of last syntax error
		other  src.XPos // source position of last non-syntax error
		msg    string   // error message of last non-syntax error
	}

	CurFunc any // *ir.Func
	Package any //*ir.Package

	LocalPkg any // *types.Pkg

	Status int

	// Per-compile counters used to mint unique synthesised names.
	// Were package-level globals; threaded here so multiple compile
	// invocations in one process don't share name spaces.
	Renameinitgen     int   // noder/noder.go (renameinit name minter)
	NoderInlgen       int   // noder/reader.go (inlined-call name minter)
	Dnamecount        int   // reflectdata/reflect.go (dname name minter)
	Slicedatagen      int   // staticdata/data.go (sliceData name minter)
	Statuniqgen       int   // staticinit/sched.go (static temp name minter)
	Mapinitgen        int   // staticinit/sched.go (map-init name minter)
	TypeAssertGen     int   // walk/expr.go (type-assert helper minter)
	InterfaceSwitchGen int  // walk/switch.go (iface-switch helper minter)
	GlobClosgen       int32 // ir/func.go (closure name minter)

	// Per-compile noder reader maps. Type-asserted at use site to
	// avoid an import cycle (noder imports base, not the other
	// direction). Were package-level globals; same per-Invocation
	// rationale as the counters above.
	NoderObjReader        any // map[*types.Sym]noder.pkgReaderIndex
	NoderBodyReader       any // map[*ir.Func]noder.pkgReaderIndex
	NoderImportBodyReader any // map[*types.Sym]noder.pkgReaderIndex
	NoderTodoBodies       any // []*ir.Func — pending function bodies during readBodies
	NoderTodoDicts        any // []func()    — pending dictionary constructors during readBodies

	// Per-compile escape caches.
	EscapeSynthRegistered any // map[string]*ir.Func — F4 forwarder compute-fn registry

	// Per-compile staticinit map-init bookkeeping. Stored on
	// Invocation so AddKeepRelocations / dwarfgen lookups don't
	// rely on package-level globals.
	StaticinitVarToMapInit any // map[*ir.Name]*ir.Func
	StaticinitMapInitToVar any // map[*ir.Func]*ir.Name

	// Per-function walk caches. Set on entry to walk.Walk, cleared
	// on exit (via defer). Stored on Invocation rather than as
	// package vars so concurrent compile invocations don't clobber
	// each other's transient walk state.
	WalkStaticValues any // map[ir.Node]ir.Node — findStaticValues result
	WalkEscapeBoxes  any // map[*ir.Name]*ir.Name — promoted-EscCandidate boxes

	// pkginit asan instrumentation tables — populated only under
	// -asan, deterministic-order via slice paired with the map.
	PkginitInstrumentGlobalsMap   any // map[string]ir.Node
	PkginitInstrumentGlobalsSlice any // []ir.Node

	// Largest size of an .L_zero buffer needed by reflectdata.ZeroAddr
	// during this compile. Emitted as a single DUPOK RODATA symbol at
	// finalize time.
	ReflectdataZeroSize int64

	// Per-compile noder wrapper-type bookkeeping. Drained by
	// MakeWrappers / wrapMethodValue at end of unified IR reading;
	// without per-Invocation storage two compiles would queue each
	// other's wrappers.
	NoderNeedWrapperTypes        any // []*types.Type
	NoderHaveWrapperTypes        any // []*types.Type
	NoderNeedMethodValueWrappers any // []noder.methodValueWrapper
	NoderHaveMethodValueWrappers any // []noder.methodValueWrapper

	// The pkgReader for the package currently being compiled.
	// Used by importedDef to distinguish local-package symbols
	// from imported ones; per-Invocation so two compiles can
	// each have their own local reader.
	NoderLocalPkgReader any // *noder.pkgReader

	// Set of LSyms for outlined map.init.NNN functions, used by
	// weakenGlobalMapInitRelocs to flag R_WEAK references between
	// init functions and their outlined map initializers.
	SsagenGlobalMapInitLsyms any // map[*obj.LSym]struct{}

	// nowritebarrierrec checker — set when -d=nowritebarrier… is on.
	// Per-compile so two parallel compiles don't share the call-graph
	// state.
	SsagenNowritebarrierrecCheck any // *ssagen.nowritebarrierrecChecker

	// typecheck.DeclFunc / FinishFuncBody push and pop CurFunc onto
	// this stack. Per-compile because CurFunc itself is per-compile;
	// concurrent compiles would otherwise corrupt each other.
	TypecheckFuncStack any // []*ir.Func

	// staticdata.FuncSym: list of *ir.Name needing function-value
	// symbols, populated concurrently from the backend (mutex-
	// protected) and consumed by WriteFuncSyms at end of compile.
	StaticdataFuncsymsMu sync.Mutex
	StaticdataFuncsyms   any // []*ir.Name

	// gd compile loop: functions waiting to be backend-compiled.
	// Populated by enqueueFunc, drained by compileFunctions.
	GdCompileQueue any // []*ir.Func

	// reflectdata pending itab EscMask slots — populated by writeITab
	// while emitting itabs and consumed by FinalizeItabMasks after
	// escape analysis. Per-compile because each Invocation has its
	// own escape state and itab list.
	ReflectdataPendingItabMasks any // []reflectdata.pendingItabMask

	// reflectdata runtime-type-descriptor work queues. signatmu/gcsymmu
	// guard concurrent access from the parallel SSA backend; signatset
	// dedups, signatslice is the FIFO of types still needing emit, and
	// gcsymset tracks which types' GC bitmaps have already been
	// emitted.
	ReflectdataSignatMu    sync.Mutex
	ReflectdataSignatSet   any // map[*types.Type]struct{}
	ReflectdataSignatSlice any // []reflectdata.typeAndStr
	ReflectdataGcsymMu     sync.Mutex
	ReflectdataGcsymSet    any // map[*types.Type]struct{}

	// logopt diagnostic accumulator. The mutex guards concurrent
	// appends from the parallel SSA backend; the slice is sorted
	// by source position at FlushLoggedOpts time.
	LogoptMu         sync.Mutex
	LogoptLoggedOpts any // []*logopt.LoggedOpt

	// inlheur per-compile heuristic state. Stored on Invocation so
	// concurrent compile invocations don't share fnInlHeur entries
	// or call-site tables. InlheurTornDown replaces the previous
	// nil-as-signal pattern (TearDown used to set fpmap=nil to
	// indicate "main inlining pass complete").
	InlheurFpmap            any  // map[*ir.Func]inlheur.fnInlHeur
	InlheurTornDown         bool // TearDown was called; new analyzeFunc calls become no-ops
	InlheurCallSiteTab      any  // inlheur.CallSiteTab — current fn's table
	InlheurAllCallSites     any  // inlheur.CallSiteTab — accumulated across whole compile (debug)
	InlheurScoreCacheTab    any  // inlheur.CallSiteTab — reused across ScoreCalls invocations
	InlheurScoreCacheCallsl any  // []*inlheur.CallSite — reused list buffer

	// typecheck imported-type → descriptor index mapping. Populated
	// by SetBaseTypeIndex during noder; consumed by reflectdata's
	// type-descriptor emit. Per-Invocation so two compiles don't
	// collide on overlapping type pointers (interned per-process,
	// but the descriptor indices are per-compile).
	TypecheckTypeSymIdx any // map[*types.Type][2]int64

	// types Phase-G outBuf marker symbols. Each Invocation has its
	// own LocalPkg, so the .outBufK Syms can't be shared across
	// invocations (Pkg pointer is per-Invocation). Lazy-initialised
	// on first outBufSym(gd, k) call.
	TypesOutBufSyms any // [32]*types.Sym

	// types.NewPkg interning. Was a package-level pkgMap that
	// would alias Pkgs (and their populated Syms tables) across
	// compile invocations in one process; the second invocation's
	// InitRuntime would then trip "importsym of symbol that
	// already exists". Lazy-initialised on first
	// types.NewPkg(gd, ...) call.
	TypesPkgMap any // map[string]*types.Pkg

	// ir.Pkgs (well-known pseudo-packages: Runtime, InternalMaps,
	// Itab, Go, Coverage). Was a package-level struct; per-
	// Invocation so the Pkg pointers are interned in this gd's
	// TypesPkgMap. Lazy-initialised on first ir.Pkgs(gd) call.
	IrPkgs any // *ir.PkgsStruct

	// types.BuiltinPkg / UnsafePkg / BlankSym — were package-level
	// vars wired up in InitUniverse. Per-Invocation so concurrent
	// compile invocations in the same process don't race on the
	// Pkgs' Syms maps during init or subsequent Lookups.
	TypesBuiltinPkg any // *types.Pkg
	TypesUnsafePkg  any // *types.Pkg
	TypesBlankSym   any // *types.Sym

	// SsaConfig / SsaCaches — were package-level `ssaConfig` /
	// `ssaCaches` in ssagen. Per-Invocation so concurrent
	// host.Run invocations don't race on InitConfig overwriting
	// the shared values.
	SsaConfig any // *ssa.Config
	SsaCaches any // []ssa.Cache

	// SiggenSet shadows the per-Sym symSiggen flag for use sites
	// that may operate on shared types.Sym pointers (BuiltinPkg /
	// UnsafePkg / nopkg). Concurrent host.Run invocations would
	// otherwise race on the global Siggen flag and trip the
	// "already generated wrapper" assertion in
	// noder.methodWrapper / reflectdata.writeType. Lazy-
	// initialised; opaque to avoid base→types import cycle. Use
	// types.SiggenIn / types.SetSiggenIn helpers.
	SiggenSet any // map[*types.Sym]bool
	SiggenMu  sync.Mutex

	// Defercalc / DeferredTypeStack — were package-level
	// `defercalc int` / `deferredTypeStack []*Type` in
	// cmd/compile/internal/types. Per-Invocation so concurrent
	// in-process compile invocations bracket their CheckSize
	// deferrals independently. DeferredTypeStack stores
	// []*types.Type (any to avoid base→types import cycle).
	Defercalc         int
	DeferredTypeStack []any

	// CalcSizeDisabled — was a package-level
	// `var CalcSizeDisabled bool` in types/size.go. Set true
	// during gd's parallel backend phase to catch CalcSize
	// calls that would race on shared Type fields. Per-
	// Invocation so concurrent host.Run calls don't leak each
	// other's flag state.
	CalcSizeDisabled bool

	// ProgArray — was the package-level
	// `var sharedProgArray = new([10000]obj.Prog)` in
	// cmd/compile/internal/objw. NewProgs slices this array per
	// worker; concurrent host.Run invocations all using
	// `sharedProgArray[sz*worker:sz*(worker+1)]` raced on the
	// same memory. Per-Invocation so each gd has its own
	// backing array. Type is *[10000]obj.Prog (any to avoid
	// base→obj import cycle in this struct).
	ProgArray     any // *[10000]obj.Prog
	ProgArrayOnce sync.Once

	// IrSyms — was `ir.Syms symsStruct` package-level. Holds
	// runtime LSyms (Memmove, Newproc, GCWriteBarrier[],
	// MallocGC*, etc.) populated in ssagen.InitConfig from
	// gd.Ctxt.Lookup. Per-Invocation so the LSyms remain
	// Ctxt-local; otherwise concurrent host.Run invocations'
	// InitConfigs overwrite each other's entries and emitted
	// relocations point at the wrong invocation's LSym.
	IrSyms any // *ir.SymsStruct

	// Pathsyms maps each types.Pkg to the importpath LSym
	// (`type:.importpath.<prefix>.`) emitted for it in this
	// invocation. Was a `Pathsym *obj.LSym` field on types.Pkg —
	// process-shared Pkgs (BuiltinPkg, UnsafePkg, the nopkg used
	// for synthetic struct field Syms via makefield, etc.) caused
	// the LSym to leak across in-process invocations: invocation 1
	// populated Pathsym with an LSym from its Ctxt, invocation 2
	// reused that LSym in relocation sym-refs, but the LSym's
	// stale {PkgIdxHashed, SymIdx} pointed outside invocation 2's
	// hashed-defs section, and the linker tripped on
	// out-of-range index when reading invocation 2's .o file.
	// Storing per-Invocation keeps the LSym Ctxt-local.
	Pathsyms any // map[*types.Pkg]*obj.LSym

	// PathsymsMu serializes dimportpath under the parallel backend.
	// Two SSA workers reaching dimportpath for the same *types.Pkg
	// at the same time would both miss the cache, both Lookup the
	// same LSym in gd.Ctxt, and both call objw.Global on it — the
	// linker pass then trips on "symbol type:.importpath.X. redeclared".
	PathsymsMu sync.Mutex

	// walk.scasetype's cached *types.Type. Was a package-level
	// `var scase`; pinned invocation 1's LocalPkg-local Syms for
	// the "c" / "elem" fields, breaking selector lookups in later
	// invocations. Per-Invocation so each compile builds scase
	// against its own LocalPkg.
	WalkScaseType any // *types.Type

	// inline package's PGO maps. Were package-level `var` maps,
	// one of which (candHotEdgeMap) is written by PGOInlinePrologue
	// in invocation A while invocation B reads it from inlineCostOK,
	// triggering "concurrent map read and map write" under cmd/go's
	// outer parallelism. The maps are stored as `any` here to keep
	// base out of the inline import graph; helpers in inline/inl.go
	// hand back typed views.
	InlPgoCandHotCalleeMap any // map[*pgoir.IRNode]struct{}
	InlPgoHasHotCall       any // map[*ir.Func]struct{}
	InlPgoCandHotEdgeMap   any // map[pgoir.CallSiteInfo]struct{}

	// Per-Invocation PGO inline thresholds; were package-level vars
	// in cmd/compile/internal/inline. Concurrent invocations with
	// different debug knobs would have raced on the writes in
	// PGOInlinePrologue.
	InlPgoHotCallSiteThresholdPercent    float64
	InlPgoCDFHotCallSiteThresholdPercent float64
	InlPgoHotMaxBudget                   int32
}
